"""initial schema for civixa module 1

Revision ID: ab40aa10014d
Revises: 
Create Date: 2026-09-06 17:59:27.256134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab40aa10014d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milestones', 'sequence_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_project_milestone_sequence', 'milestones', ['project_id', 'sequence_order'])
    op.create_unique_constraint('uq_project_milestone_title', 'milestones', ['project_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_milestone_title', 'milestones', type_='unique')
    op.drop_constraint('uq_project_milestone_sequence', 'milestones', type_='unique')
    op.alter_column('milestones', 'sequence_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
